import type {
  Signal,
  Engagement,
  Requirement,
  ChangeRequest,
  UATDefect,
  MeetingNote,
  LegacySystem,
  KPI,
  AuditEntry,
  Notification,
} from './types';

export const engagements: Engagement[] = [
  { name: 'Northstar Retail', code: 'NSR-24', phase: 'UAT → Go-live', score: 82, status: 'On track', initials: 'NR', color: 'bg-sky-100 text-sky-700', startDate: '2025-03-15' },
  { name: 'Meridian Health', code: 'MDH-18', phase: 'Sprint 08', score: 67, status: 'Needs attention', initials: 'MH', color: 'bg-emerald-100 text-emerald-700', startDate: '2025-05-01' },
  { name: 'Atlas Finance', code: 'ATF-31', phase: 'Discovery', score: 91, status: 'On track', initials: 'AF', color: 'bg-amber-100 text-amber-700', startDate: '2025-07-20' },
];

export const signals: Signal[] = [
  { id: 'SIG-024', type: 'Scope drift', title: 'New request detected in steering note', caseId: 'REQ-184 · Northstar', confidence: 94, materiality: '18h / 4 days', risk: 'High', evidence: '"Can we also include bulk export for regional admins?" appears in the 08 Aug steering note. No CR linked.', action: 'Open a change request and confirm commercial impact before sprint entry.', source: 'Meeting note · 08 Aug 2025 · page 2', approved: false },
  { id: 'SIG-019', type: 'Requirement quality', title: 'Story entered development without acceptance criteria', caseId: 'REQ-172 · Meridian', confidence: 98, materiality: 'Medium', risk: 'Medium', evidence: 'Story committed on 04 Aug with acceptance criteria field empty. Three downstream UAT defects link to the same story.', action: 'Add a completeness gate before sprint commitment.', source: 'Requirement register · REQ-172 · v3', approved: false },
  { id: 'SIG-017', type: 'Late change', title: 'Requirement edited after sprint commitment', caseId: 'REQ-155 · Atlas', confidence: 91, materiality: '26h / 6 days', risk: 'High', evidence: 'Definition changed after sprint lock on 29 Jul. Effort moved from 16h to 42h.', action: 'Route to PM + client sponsor for impact review.', source: 'Version history · REQ-155 · 29 Jul', approved: false },
  { id: 'SIG-011', type: 'Rework', title: 'UAT item reopened more than once', caseId: 'DEF-044 · Meridian', confidence: 96, materiality: '12h / 2 cycles', risk: 'Medium', evidence: 'Defect reopened twice after regression test. Root-cause hypothesis: missing negative-path acceptance criteria.', action: 'Require negative-path test evidence before closure.', source: 'UAT defect log · DEF-044', approved: false },
  { id: 'SIG-008', type: 'SLA breach', title: 'Client approval time exceeds SOP target', caseId: 'CR-018 · Northstar', confidence: 88, materiality: '3.4 days wait', risk: 'Medium', evidence: 'Approval took 5.4 days against SOP target of 2 days. Two follow-ups recorded in the case timeline.', action: 'Escalate with a client-safe status line and named owner.', source: 'SOP-04 · approval latency rule', approved: false },
  { id: 'SIG-031', type: 'Scope drift', title: 'Dependency added after sprint plan locked', caseId: 'REQ-201 · Meridian', confidence: 85, materiality: '8h / 2 days', risk: 'Medium', evidence: 'New dependency on Atlas Data Hub added after sprint 08 was locked. No impact assessment on file.', action: 'Run the Change Impact Simulator and route to PM for sign-off.', source: 'Sprint board · Sprint 08 · 06 Aug', approved: false },
  { id: 'SIG-006', type: 'Late change', title: 'Estimated effort changed materially after planning', caseId: 'REQ-148 · Northstar', confidence: 89, materiality: '20h delta', risk: 'Medium', evidence: 'Effort estimate moved from 12h to 32h after planning poker. Story was already committed.', action: 'Flag for PM review and update sprint burndown.', source: 'Requirement register · REQ-148 · v2', approved: true, approvedBy: 'PM' },
  { id: 'SIG-003', type: 'Requirement quality', title: 'Clarification loop on requirement text', caseId: 'REQ-165 · Atlas', confidence: 82, materiality: 'Low', risk: 'Low', evidence: 'Three clarification cycles on the same requirement. Source: client email thread.', action: 'Draft a wording clarification for BA or product owner review.', source: 'Email thread · 30 Jul – 02 Aug', approved: false },
  { id: 'SIG-014', type: 'SLA breach', title: 'Scope-approval latency breach on CR-021', caseId: 'CR-021 · Meridian', confidence: 79, materiality: '2.1 days wait', risk: 'Low', evidence: 'Approval pending for 4.1 days against SOP target of 2 days. One follow-up sent.', action: 'Send a client-safe reminder with named owner.', source: 'Change request log · CR-021', approved: false },
  { id: 'SIG-027', type: 'Rework', title: 'UAT defect recurrence on REQ-172', caseId: 'DEF-051 · Meridian', confidence: 92, materiality: '6h / 1 cycle', risk: 'Medium', evidence: 'Same root cause as DEF-044. Acceptance criteria still missing for linked requirement.', action: 'Block closure until acceptance criteria are added and negative-path tests pass.', source: 'UAT defect log · DEF-051', approved: false },
  { id: 'SIG-033', type: 'Scope drift', title: 'New request in meeting notes without CR', caseId: 'REQ-210 · Atlas', confidence: 87, materiality: '12h / 3 days', risk: 'High', evidence: '"We need SSO for partner portals" mentioned in 06 Aug sync. No CR linked.', action: 'Create a change request and assess commercial impact.', source: 'Meeting note · 06 Aug 2025', approved: false },
  { id: 'SIG-009', type: 'Late change', title: 'Requirement version bumped after sprint lock', caseId: 'REQ-159 · Northstar', confidence: 90, materiality: '14h / 3 days', risk: 'High', evidence: 'Requirement version went from v2 to v4 after sprint 07 lock. Two field edits to acceptance criteria.', action: 'Route to client sponsor + PM + finance for impact review.', source: 'Version history · REQ-159 · 02 Aug', approved: false },
];

export const requirements: Requirement[] = [
  { id: 'REQ-172', text: 'Checkout flow supports guest checkout', source: 'Client PRD', hasAcceptanceCriteria: false, owner: 'R. Kapoor', linkedStory: 'STR-204', version: 3, clarityScore: 42, engagement: 'Meridian Health' },
  { id: 'REQ-155', text: 'Policy admin screen with bulk edit', source: 'Client workshop', hasAcceptanceCriteria: true, owner: 'S. Iyer', linkedStory: 'STR-188', version: 5, clarityScore: 61, engagement: 'Atlas Finance' },
  { id: 'REQ-184', text: 'Regional admin bulk order export', source: 'Steering meeting', hasAcceptanceCriteria: false, owner: 'Unassigned', linkedStory: '', version: 1, clarityScore: 28, engagement: 'Northstar Retail' },
  { id: 'REQ-148', text: 'Payment retry logic for failed transactions', source: 'Client PRD', hasAcceptanceCriteria: true, owner: 'P. Menon', linkedStory: 'STR-160', version: 2, clarityScore: 74, engagement: 'Northstar Retail' },
  { id: 'REQ-165', text: 'SSO integration for partner portals', source: 'Client email', hasAcceptanceCriteria: false, owner: 'A. Shah', linkedStory: '', version: 1, clarityScore: 38, engagement: 'Atlas Finance' },
  { id: 'REQ-159', text: 'Inventory sync with warehouse system', source: 'Client PRD', hasAcceptanceCriteria: true, owner: 'R. Kapoor', linkedStory: 'STR-175', version: 4, clarityScore: 55, engagement: 'Northstar Retail' },
  { id: 'REQ-201', text: 'Customer master data validation', source: 'Discovery workshop', hasAcceptanceCriteria: true, owner: 'S. Iyer', linkedStory: 'STR-230', version: 2, clarityScore: 68, engagement: 'Meridian Health' },
  { id: 'REQ-210', text: 'Partner portal SSO', source: 'Meeting note', hasAcceptanceCriteria: false, owner: 'Unassigned', linkedStory: '', version: 1, clarityScore: 25, engagement: 'Atlas Finance' },
];

export const changeRequests: ChangeRequest[] = [
  { id: 'CR-018', description: 'Add bulk export for regional admins', linkedRequirement: 'REQ-184', status: 'Open', riskTier: 'High', hoursEstimate: 18, approvalStatus: 'Pending', approver: 'Client sponsor + PM + finance', engagement: 'Northstar Retail' },
  { id: 'CR-021', description: 'Add SSO for partner portals', linkedRequirement: 'REQ-165', status: 'Open', riskTier: 'Medium', hoursEstimate: 12, approvalStatus: 'Pending', approver: 'PM + product owner', engagement: 'Meridian Health' },
  { id: 'CR-014', description: 'Update inventory sync frequency to real-time', linkedRequirement: 'REQ-159', status: 'Approved', riskTier: 'Medium', hoursEstimate: 14, approvalStatus: 'Approved', approver: 'Priya Menon · PM', engagement: 'Northstar Retail' },
  { id: 'CR-025', description: 'Add negative-path test evidence requirement', linkedRequirement: 'REQ-172', status: 'Approved', riskTier: 'Low', hoursEstimate: 4, approvalStatus: 'Approved', approver: 'R. Kapoor · BA', engagement: 'Meridian Health' },
];

export const uatDefects: UATDefect[] = [
  { id: 'DEF-044', description: 'Checkout fails on empty cart state', linkedRequirement: 'REQ-172', recurrence: true, rootCauseHypothesis: 'Missing negative-path acceptance criteria', engagement: 'Meridian Health' },
  { id: 'DEF-051', description: 'Checkout fails on expired session token', linkedRequirement: 'REQ-172', recurrence: true, rootCauseHypothesis: 'Same root cause as DEF-044', engagement: 'Meridian Health' },
  { id: 'DEF-038', description: 'Bulk edit saves without validation', linkedRequirement: 'REQ-155', recurrence: false, rootCauseHypothesis: 'Validation rule not in acceptance criteria', engagement: 'Atlas Finance' },
  { id: 'DEF-060', description: 'Payment retry sends duplicate webhook', linkedRequirement: 'REQ-148', recurrence: false, rootCauseHypothesis: 'Idempotency key not enforced', engagement: 'Northstar Retail' },
];

export const meetingNotes: MeetingNote[] = [
  { id: 'MN-008', rawText: 'Priya: UAT is on track for the core checkout flow.\n\nClient asked if regional admins can export bulk orders. This was not in the original scope.\n\nRavi to confirm effort by Thursday. Sarah to share the negative-path test evidence.\n\nNext sync: 14 Aug.', date: '08 Aug 2025', attendees: ['Priya', 'Ravi', 'Sarah', 'Northstar team'], engagement: 'Northstar Retail' },
  { id: 'MN-006', rawText: 'Discussion: Partner portal SSO is now a hard requirement. We need SSO for partner portals. No CR yet.\n\nSprint 08 dependency on Atlas Data Hub added late. Need impact assessment.\n\nAction: A. Shah to draft CR by Friday.', date: '06 Aug 2025', attendees: ['A. Shah', 'V. Rao', 'Atlas team'], engagement: 'Atlas Finance' },
];

export const legacySystems: LegacySystem[] = [
  {
    name: 'Nimbus ERP',
    type: 'On-prem ERP',
    team: 'Finance operations',
    criticality: 'High',
    description: 'Core financials, procurement, and order management system.',
    owner: 'Enterprise Platforms team',
    lastUpdate: 'July 2024',
    authMethod: 'Service account + VPN',
    environments: ['dev', 'staging', 'prod'],
    endpoints: ['/api/v1/orders', '/api/v1/inventory', '/api/v1/procurement'],
    dataClassification: 'Financial, Confidential',
    quirks: ['Not documented — confirm with system owner before implementing retries or assuming idempotency.'],
    version: 3,
    sourceMaterials: ['README', 'Access SOP', 'Owner notes', 'Integration spec v2'],
    generatedDate: '08 Aug 2025',
    confidence: 'Verify with owner',
  },
  {
    name: 'Cobalt API Gateway',
    type: 'Proprietary API',
    team: 'Integration layer',
    criticality: 'Critical',
    description: 'Routes all external partner integrations and enforces rate limits.',
    owner: 'Platform Engineering',
    lastUpdate: 'May 2025',
    authMethod: 'OAuth 2.0 client credentials',
    environments: ['dev', 'staging', 'prod'],
    endpoints: ['/oauth/token', '/partner/v1/orders', '/partner/v1/shipments'],
    dataClassification: 'PII, Financial',
    quirks: ['Token expiry is 10 minutes, not 60 as documented.', 'Rate limit resets at midnight UTC, not local time.'],
    version: 2,
    sourceMaterials: ['API spec', 'Runbook', 'Vendor docs'],
    generatedDate: '06 Aug 2025',
    confidence: 'High',
  },
  {
    name: 'Orion Mainframe',
    type: 'Mainframe',
    team: 'Policy administration',
    criticality: 'Critical',
    description: 'Hosts the policy administration and claims processing modules.',
    owner: 'Legacy Systems team',
    lastUpdate: 'March 2023',
    authMethod: 'VPN + mainframe credentials',
    environments: ['staging', 'prod'],
    endpoints: ['TN3270 terminal', 'Batch file drop', 'MQ queue POLICY.IN'],
    dataClassification: 'PII, Financial, Regulatory',
    quirks: ['No dev environment available — confirm with system owner.', 'Batch jobs run 02:00–04:00 UTC; avoid integration calls during this window.'],
    version: 1,
    sourceMaterials: ['Mainframe runbook', 'Operations manual'],
    generatedDate: '01 Aug 2025',
    confidence: 'Verify with owner',
  },
  {
    name: 'Atlas Data Hub',
    type: 'Legacy database',
    team: 'Customer master',
    criticality: 'High',
    description: 'Central customer master data repository with real-time sync requirements.',
    owner: 'Data Engineering',
    lastUpdate: 'June 2025',
    authMethod: 'Database service account + IP allowlist',
    environments: ['dev', 'staging', 'prod'],
    endpoints: ['jdbc:atlas://db.internal:5432/customer', 'REST /api/v1/customer/{id}'],
    dataClassification: 'PII, Confidential',
    quirks: ['Connection pool max is 10 — do not exceed.', 'Sync lag of up to 30 seconds is normal during peak hours.'],
    version: 4,
    sourceMaterials: ['DB schema doc', 'Data dictionary', 'Sync architecture doc'],
    generatedDate: '10 Aug 2025',
    confidence: 'High',
  },
  {
    name: 'Mercury SFTP',
    type: 'File exchange',
    team: 'Partner settlements',
    criticality: 'Medium',
    description: 'Batch file exchange for partner settlement and reconciliation files.',
    owner: 'Operations',
    lastUpdate: 'January 2025',
    authMethod: 'SSH key + IP allowlist',
    environments: ['staging', 'prod'],
    endpoints: ['sftp://mercury.internal:22/settlements/', 'sftp://mercury.internal:22/recon/'],
    dataClassification: 'Financial',
    quirks: ['Files must use CRLF line endings — LF files are silently rejected.', 'Max file size 500MB; larger files must be split.'],
    version: 2,
    sourceMaterials: ['SFTP runbook', 'Partner onboarding guide'],
    generatedDate: '28 Jul 2025',
    confidence: 'High',
  },
  {
    name: 'Helios IAM',
    type: 'On-prem identity',
    team: 'Authentication',
    criticality: 'Critical',
    description: 'Central identity and access management for all on-prem systems.',
    owner: 'Security Engineering',
    lastUpdate: 'April 2025',
    authMethod: 'LDAP bind + service account',
    environments: ['dev', 'staging', 'prod'],
    endpoints: ['ldap://helios.internal:389', 'ldaps://helios.internal:636', 'REST /api/v1/users/{id}'],
    dataClassification: 'PII, Security',
    quirks: ['LDAP search timeout is 5 seconds — use pagination for large result sets.', 'Service account passwords rotate every 90 days; subscribe to the rotation notification channel.'],
    version: 5,
    sourceMaterials: ['IAM architecture doc', 'LDAP schema', 'Security policy'],
    generatedDate: '12 Aug 2025',
    confidence: 'High',
  },
];

export const kpis: KPI[] = [
  { name: 'Requirement clarity rate', baseline: '72%', target: '85%', observed: '79%', status: 'Observed', movement: '↑ 7 pts', formula: 'Complete requirements ÷ total', better: 'Higher' },
  { name: 'Clarification-loop rate', baseline: '34%', target: '< 15%', observed: '21%', status: 'Modeled', movement: '↓ 13 pts', formula: 'Requirements with ≥2 clarification cycles ÷ total', better: 'Lower' },
  { name: 'Late-change ratio', baseline: '31%', target: '< 15%', observed: '18%', status: 'Modeled', movement: '↓ 13 pts', formula: 'Material changes after sprint commitment ÷ total changes', better: 'Lower' },
  { name: 'Reopen / rework rate', baseline: '24%', target: '< 10%', observed: '14%', status: 'Observed', movement: '↓ 10 pts', formula: 'Reopened items ÷ completed items', better: 'Lower' },
  { name: 'UAT defect recurrence', baseline: '18%', target: '< 5%', observed: '8%', status: 'Observed', movement: '↓ 10 pts', formula: 'Repeat defects tied to same requirement ÷ total UAT defects', better: 'Lower' },
  { name: 'Requirement-to-ready time', baseline: '12.4d', target: '< 7d', observed: '8.2d', status: 'Directional', movement: '↓ 4.2d', formula: 'Ready timestamp − request timestamp', better: 'Shorter' },
  { name: 'Scope-approval latency', baseline: '4.8d', target: '< 2d', observed: '2.6d', status: 'Client-validated', movement: '↓ 2.2d', formula: 'Approval timestamp − change-request timestamp', better: 'Shorter' },
  { name: 'Traceability completeness', baseline: '58%', target: '90%', observed: '76%', status: 'Directional', movement: '↑ 18 pts', formula: 'Items linked requirement→story→test ÷ all active items', better: 'Higher' },
];

export const auditEntries: AuditEntry[] = [
  { id: 'AUD-038', suggestion: 'Add completeness gate', riskTier: 'Medium', decision: 'Approved', by: 'Priya Menon · PM', timestamp: 'Today, 10:42', engagement: 'Meridian Health' },
  { id: 'AUD-037', suggestion: 'Scope request CR-018', riskTier: 'High', decision: 'Modified', by: 'A. Shah · Client sponsor', timestamp: 'Today, 09:18', engagement: 'Northstar Retail' },
  { id: 'AUD-036', suggestion: 'UAT evidence pack', riskTier: 'Low', decision: 'Approved', by: 'R. Kapoor · BA', timestamp: 'Yesterday, 16:04', engagement: 'Meridian Health' },
  { id: 'AUD-035', suggestion: 'Approval SLA escalation', riskTier: 'Medium', decision: 'Rejected', by: 'Priya Menon · PM', timestamp: 'Yesterday, 14:22', engagement: 'Northstar Retail' },
  { id: 'AUD-034', suggestion: 'Dependency register', riskTier: 'Medium', decision: 'Approved', by: 'V. Rao · Governance', timestamp: '06 Aug, 11:55', engagement: 'Atlas Finance' },
  { id: 'AUD-033', suggestion: 'Effort re-estimate flag REQ-148', riskTier: 'Medium', decision: 'Approved', by: 'Priya Menon · PM', timestamp: '05 Aug, 15:30', engagement: 'Northstar Retail' },
  { id: 'AUD-032', suggestion: 'Clarification wording for REQ-165', riskTier: 'Low', decision: 'Modified', by: 'A. Shah · Product owner', timestamp: '04 Aug, 10:12', engagement: 'Atlas Finance' },
];

export const notifications: Notification[] = [
  { id: 'N-01', type: 'signal', title: 'New signal: SIG-024', detail: 'Scope drift detected in Northstar steering note', time: '8 min ago', read: false },
  { id: 'N-02', type: 'approval', title: 'Approval overdue: CR-018', detail: 'High-risk change request pending 3.4 days', time: '1 hr ago', read: false },
  { id: 'N-03', type: 'sla', title: 'SLA breach: CR-021', detail: 'Scope approval latency exceeded SOP target', time: '2 hr ago', read: false },
  { id: 'N-04', type: 'digest', title: 'Weekly digest ready', detail: 'Week 32 Client Trust Digest drafted by AI', time: '3 hr ago', read: true },
  { id: 'N-05', type: 'signal', title: 'New signal: SIG-033', detail: 'Scope drift in Atlas meeting notes — partner SSO', time: '5 hr ago', read: true },
];

export const portfolioActions = [
  { name: 'Completeness gate', impact: 77, feasibility: 77, color: 'bg-blue-600', score: 84.2, dimensions: [
    { name: 'Business impact', weight: '25%', score: 91 },
    { name: 'Feasibility', weight: '20%', score: 84 },
    { name: 'AI / automation fit', weight: '20%', score: 88 },
    { name: 'Data readiness', weight: '15%', score: 79 },
    { name: 'Risk', weight: '10%', score: 72 },
    { name: 'Time-to-value', weight: '10%', score: 90 },
  ], risk: 'Medium' as const, approver: 'PM + product owner', description: 'Prevent stories entering development without acceptance criteria and traceability links.' },
  { name: 'Approval SLA lane', impact: 62, feasibility: 61, color: 'bg-emerald-500', score: 78.6, dimensions: [
    { name: 'Business impact', weight: '25%', score: 78 },
    { name: 'Feasibility', weight: '20%', score: 82 },
    { name: 'AI / automation fit', weight: '20%', score: 75 },
    { name: 'Data readiness', weight: '15%', score: 80 },
    { name: 'Risk', weight: '10%', score: 85 },
    { name: 'Time-to-value', weight: '10%', score: 70 },
  ], risk: 'Low' as const, approver: 'BA or product owner', description: 'Create a dedicated approval lane with SLA tracking and auto-escalation.' },
  { name: 'UAT evidence pack', impact: 48, feasibility: 74, color: 'bg-amber-500', score: 72.4, dimensions: [
    { name: 'Business impact', weight: '25%', score: 62 },
    { name: 'Feasibility', weight: '20%', score: 88 },
    { name: 'AI / automation fit', weight: '20%', score: 80 },
    { name: 'Data readiness', weight: '15%', score: 75 },
    { name: 'Risk', weight: '10%', score: 78 },
    { name: 'Time-to-value', weight: '10%', score: 50 },
  ], risk: 'Low' as const, approver: 'BA or product owner', description: 'Standardize UAT evidence packs with negative-path test requirements.' },
  { name: 'Scope change intake', impact: 70, feasibility: 40, color: 'bg-slate-500', score: 68.1, dimensions: [
    { name: 'Business impact', weight: '25%', score: 85 },
    { name: 'Feasibility', weight: '20%', score: 52 },
    { name: 'AI / automation fit', weight: '20%', score: 70 },
    { name: 'Data readiness', weight: '15%', score: 65 },
    { name: 'Risk', weight: '10%', score: 60 },
    { name: 'Time-to-value', weight: '10%', score: 55 },
  ], risk: 'High' as const, approver: 'Client sponsor + PM + finance', description: 'Formalize scope change intake with commercial impact assessment.' },
  { name: 'Dependency register', impact: 36, feasibility: 52, color: 'bg-slate-400', score: 58.3, dimensions: [
    { name: 'Business impact', weight: '25%', score: 48 },
    { name: 'Feasibility', weight: '20%', score: 65 },
    { name: 'AI / automation fit', weight: '20%', score: 55 },
    { name: 'Data readiness', weight: '15%', score: 60 },
    { name: 'Risk', weight: '10%', score: 70 },
    { name: 'Time-to-value', weight: '10%', score: 50 },
  ], risk: 'Medium' as const, approver: 'PM + product owner', description: 'Maintain a live dependency register linked to sprint plans.' },
];
